//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGLStudy.Models {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeshResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeshResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenGLStudy.Models.MeshResource", typeof(MeshResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 0, 1, 2, 2, 3, 0,
        ///4, 5, 6, 6, 7, 4,
        ///8, 9, 10, 10, 11, 8,
        ///12, 13, 14, 14, 15, 12,
        ///16, 17, 18, 18, 19, 16,
        ///20, 21, 22, 22, 23, 20 的本地化字符串。
        /// </summary>
        internal static string CubeIndices {
            get {
                return ResourceManager.GetString("CubeIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -0.5f, -0.5f, -0.5f,  0.0f, 0.0f,
        ///0.5f, -0.5f, -0.5f,  1.0f, 0.0f,
        ///0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
        ///-0.5f,  0.5f, -0.5f,  0.0f, 1.0f,
        ///0.5f, -0.5f, 0.5f,  0.0f, 0.0f,
        ///-0.5f, -0.5f, 0.5f,  1.0f, 0.0f,
        ///-0.5f,  0.5f, 0.5f,  1.0f, 1.0f,
        ///0.5f,  0.5f, 0.5f,  0.0f, 1.0f,
        ///-0.5f, -0.5f, 0.5f,  0.0f, 0.0f, 
        ///-0.5f, -0.5f, -0.5f,  1.0f, 0.0f,
        ///-0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
        ///-0.5f,  0.5f, 0.5f,  0.0f, 1.0f,
        ///0.5f, -0.5f, -0.5f,  0.0f, 0.0f,
        ///0.5f, -0.5f, 0.5f,  1.0f, 0.0f,
        ///0.5f,  0.5f, 0.5f,  1.0f, 1.0f,
        ///0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CubeVertices {
            get {
                return ResourceManager.GetString("CubeVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0, 1, 2,  2, 3, 0,
        ///4, 5, 6,  6, 7, 4,
        ///8, 9, 10, 10, 11, 8,
        ///12, 13, 14, 14, 15, 12,
        ///16, 17, 18, 18, 19, 16,
        ///20, 21, 22, 22, 23, 20 的本地化字符串。
        /// </summary>
        internal static string MaterialCubeIndices {
            get {
                return ResourceManager.GetString("MaterialCubeIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -0.5f, -0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        ///0.5f, -0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        ///0.5f,  0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        ///0.5f,  0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        ///-0.5f,  0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        ///-0.5f, -0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        ///-0.5f, -0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        ///0.5f, -0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        ///0.5f,  0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        ///0.5f,  0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        ///-0.5f,  0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        ///-0.5f, -0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        ///-0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MaterialCubeVertices {
            get {
                return ResourceManager.GetString("MaterialCubeVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0, 1,  2 的本地化字符串。
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -0.5f, 0.0f, 0.0f, 0.0f, 1.0f, 
        ///0.5f,  0.0f, 0.0f, 1.0f, 1.0f,
        ///0.0f, 1.0f, 0.0f, 0.5f, 0.0f, 的本地化字符串。
        /// </summary>
        internal static string TriangleVertices {
            get {
                return ResourceManager.GetString("TriangleVertices", resourceCulture);
            }
        }
    }
}
